// generated by tools/dump_gym_schema.py from otm_gym_management transitions
import type { Schema } from './schema.generated';
export const GYM_SCHEMA: Schema = {
 "otm.gym.membership": {
  "stateField": "state",
  "states": {
   "draft": "Draft",
   "confirmed": "Confirmed",
   "active": "Active",
   "frozen": "Frozen",
   "expired": "Expired",
   "renewal_pending": "Renewal Pending",
   "renewed": "Renewed",
   "cancelled": "Cancelled"
  },
  "reason": [
   "action_freeze",
   "action_cancel"
  ],
  "actions": {
   "action_confirm": {
    "from": [
     "draft"
    ],
    "system": true
   },
   "action_activate": {
    "from": [
     "confirmed"
    ],
    "system": true
   },
   "action_freeze": {
    "from": [
     "active"
    ],
    "system": false
   },
   "action_unfreeze": {
    "from": [
     "frozen"
    ],
    "system": true
   },
   "action_expire": {
    "from": [
     "active",
     "renewal_pending"
    ],
    "system": true
   },
   "action_start_renewal": {
    "from": [
     "active",
     "expired"
    ],
    "system": false
   },
   "action_mark_contacted": {
    "from": [
     "active",
     "expired",
     "renewal_pending"
    ],
    "system": true
   },
   "action_renew": {
    "from": [
     "active",
     "expired",
     "renewal_pending"
    ],
    "system": true
   },
   "action_cancel": {
    "from": [
     "draft",
     "confirmed",
     "active"
    ],
    "system": true
   }
  }
 },
 "otm.gym.member": {
  "stateField": "status",
  "states": {
   "prospect": "Prospect",
   "active": "Active",
   "frozen": "Frozen",
   "expired": "Expired",
   "inactive": "Inactive"
  },
  "reason": [
   "action_deactivate"
  ],
  "actions": {
   "action_deactivate": {
    "from": [
     "prospect",
     "active",
     "frozen",
     "expired"
    ],
    "system": false
   },
   "action_reactivate": {
    "from": [
     "inactive"
    ],
    "system": true
   }
  }
 },
 "otm.gym.attendance": {
  "stateField": "state",
  "states": {
   "expected": "Expected",
   "present": "Present",
   "checked_out": "Checked Out",
   "absent": "Absent"
  },
  "reason": [],
  "actions": {
   "action_check_out": {
    "from": [
     "present"
    ],
    "system": true
   },
   "action_mark_absent": {
    "from": [
     "expected"
    ],
    "system": false
   }
  }
 },
 "otm.gym.appointment": {
  "stateField": "state",
  "states": {
   "scheduled": "Scheduled",
   "confirmed": "Confirmed",
   "in_progress": "In Progress",
   "completed": "Completed",
   "cancelled": "Cancelled",
   "no_show": "No Show"
  },
  "reason": [
   "action_cancel",
   "action_no_show"
  ],
  "actions": {
   "action_confirm": {
    "from": [
     "scheduled"
    ],
    "system": false
   },
   "action_start": {
    "from": [
     "scheduled",
     "confirmed"
    ],
    "system": false
   },
   "action_complete": {
    "from": [
     "confirmed",
     "in_progress"
    ],
    "system": false
   },
   "action_cancel": {
    "from": [
     "scheduled",
     "confirmed"
    ],
    "system": false
   },
   "action_no_show": {
    "from": [
     "scheduled",
     "confirmed"
    ],
    "system": false
   }
  }
 },
 "otm.gym.assessment": {
  "stateField": "state",
  "states": {
   "draft": "Draft",
   "done": "Completed"
  },
  "reason": [],
  "actions": {
   "action_complete": {
    "from": [
     "draft"
    ],
    "system": true
   }
  }
 },
 "otm.gym.workout.plan": {
  "stateField": "state",
  "states": {
   "draft": "Draft",
   "review": "Review",
   "approved": "Approved",
   "active": "Active",
   "completed": "Completed",
   "archived": "Archived"
  },
  "reason": [
   "action_reject"
  ],
  "actions": {
   "action_submit": {
    "from": [
     "draft"
    ],
    "system": false
   },
   "action_approve": {
    "from": [
     "review"
    ],
    "system": false
   },
   "action_reject": {
    "from": [
     "review"
    ],
    "system": false
   },
   "action_activate": {
    "from": [
     "approved"
    ],
    "system": true
   },
   "action_complete": {
    "from": [
     "active"
    ],
    "system": false
   },
   "action_archive": {
    "from": [
     "completed"
    ],
    "system": false
   }
  }
 },
 "otm.gym.diet.plan": {
  "stateField": "state",
  "states": {
   "draft": "Draft",
   "review": "Review",
   "approved": "Approved",
   "active": "Active",
   "completed": "Completed",
   "archived": "Archived"
  },
  "reason": [
   "action_reject"
  ],
  "actions": {
   "action_submit": {
    "from": [
     "draft"
    ],
    "system": false
   },
   "action_approve": {
    "from": [
     "review"
    ],
    "system": false
   },
   "action_reject": {
    "from": [
     "review"
    ],
    "system": false
   },
   "action_activate": {
    "from": [
     "approved"
    ],
    "system": true
   },
   "action_complete": {
    "from": [
     "active"
    ],
    "system": false
   },
   "action_archive": {
    "from": [
     "completed"
    ],
    "system": false
   }
  }
 },
 "otm.gym.payment": {
  "stateField": "state",
  "states": {
   "pending": "Pending",
   "requested": "Requested",
   "partial": "Partially Paid",
   "paid": "Paid",
   "cancelled": "Cancelled"
  },
  "reason": [
   "action_cancel",
   "action_refund"
  ],
  "actions": {
   "action_request": {
    "from": [
     "pending"
    ],
    "system": true
   },
   "action_confirm_payment": {
    "from": [
     "pending",
     "requested",
     "partial"
    ],
    "system": true
   },
   "action_refund": {
    "from": [
     "partial",
     "paid"
    ],
    "system": true
   },
   "action_cancel": {
    "from": [
     "pending",
     "requested"
    ],
    "system": false
   }
  }
 }
};
