"""Emit lib/schema.gym.generated.ts from the Odoo module's transition matrix (no Odoo needed).
usage: python tools/dump_gym_schema.py ../otm_gym_management"""
import importlib.util, json, sys, os
mod = sys.argv[1] if len(sys.argv) > 1 else '../otm_gym_management'
spec = importlib.util.spec_from_file_location('tr', os.path.join(mod, 'models/transitions.py'))
tr = importlib.util.module_from_spec(spec); spec.loader.exec_module(tr)
out = {}
for model, m in tr.TRANSITIONS.items():
    out['otm.gym.' + model if not model.startswith('otm.') else model] = {
        'stateField': m['state_field'], 'states': dict(m['states']), 'reason': list(m.get('reason', [])),
        'actions': {a: {'from': list(s['from']), 'system': bool(s.get('auto'))} for a, s in m['actions'].items()}}
open(os.path.join(os.path.dirname(__file__), '..', 'lib', 'schema.gym.generated.ts'), 'w').write(
    '// generated by tools/dump_gym_schema.py from otm_gym_management transitions\n'
    "import type { Schema } from './schema.generated';\nexport const GYM_SCHEMA: Schema = " + json.dumps(out, indent=1) + ';\n')
print(list(out))
